#!/usr/bin/env python3
"""Batch-export executable files to IDA-generated ASM files.




Example:
   python3 batch_ida_asm.py \
       --ida /opt/idapro/idat64 \
       --input /data/exe_samples \
       --output /data/asm \
       --timeout 600 \
       --recursive




For one file, --input can be an .exe path.
"""




from __future__ import annotations




import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path








IDA_EXPORTER = r'''# IDAPython script generated by batch_ida_asm.py
import os
import idaapi
import ida_ida
import ida_pro
import ida_auto
import ida_kernwin




ida_auto.auto_wait()




output_path = __OUTPUT_PATH__
os.makedirs(os.path.dirname(output_path), exist_ok=True)




# IDA 9.x exposes the database address range through ida_ida.
start_ea = ida_ida.inf_get_min_ea()
end_ea = ida_ida.inf_get_max_ea()




try:
   result = idaapi.gen_file(idaapi.OFILE_ASM, output_path,
                            start_ea, end_ea, 0)
except Exception:
   # Compatibility fallback for IDA versions exposing gen_file through idc.
   import idc
   result = idc.gen_file(idc.OFILE_ASM, output_path,
                         start_ea, end_ea, 0)




# gen_file() may return the number of bytes written.  For example,
# 328120 means that 328,120 bytes were successfully exported.  Negative
# values indicate failure.
if isinstance(result, int) and result < 0:
   raise RuntimeError("IDA failed to generate the ASM file: %r" % (result,))




if not os.path.isfile(output_path):
   raise RuntimeError("IDA reported success, but the ASM file was not created")




print("ASM_CREATED:" + output_path)
ida_pro.qexit(0)
'''

def make_ida_script(output_path: Path, temp_dir: Path) -> Path:
   script_path = temp_dir / "export_asm_ida.py"
   script_text = IDA_EXPORTER.replace(
       "__OUTPUT_PATH__", json.dumps(str(output_path.resolve()))
   )
   script_path.write_text(script_text, encoding="utf-8")
   return script_path

def find_inputs(input_path: Path, recursive: bool) -> list[Path]:
   if input_path.is_file():
       return [input_path]



   if not input_path.is_dir():
       raise FileNotFoundError(f"Input does not exist: {input_path}")



   pattern = "**/*" if recursive else "*"
   files = []
   for path in input_path.glob(pattern):
       if path.is_file() and is_executable_candidate(path):
           files.append(path)
   return sorted(files)






def is_executable_candidate(path: Path) -> bool:
   """Accept normal Windows extensions and extensionless PE files."""
   if path.suffix.lower() in {".exe", ".dll", ".sys"}:
       return True



   # Windows PE files normally begin with the ASCII bytes ``MZ``.
   try:
       with path.open("rb") as file:
           return file.read(2) == b"MZ"
   except OSError:
       return False




def export_one(ida_path: Path, input_file: Path, output_dir: Path,
              timeout_seconds: int, skip_existing: bool) -> bool:
   output_file = output_dir / f"{input_file.stem}.asm"
   log_file = output_dir / f"{input_file.stem}.ida.log"




   if skip_existing and output_file.is_file() and output_file.stat().st_size > 0:
       print(f"[SKIP]  {input_file} (ASM already exists)")
       return True




   with tempfile.TemporaryDirectory(prefix="ida_batch_") as temp_name:
       temp_dir = Path(temp_name)
       script_path = make_ida_script(output_file, temp_dir)
       database_path = temp_dir / input_file.stem




       command = [
           str(ida_path),
           "-A",                         # autonomous/no-user-interface mode
           f"-L{log_file}",              # IDA log file
           f"-o{database_path}",         # keep the IDB outside the input tree
           f"-S{script_path}",           # run the generated IDAPython script
           str(input_file.resolve()),
       ]




       print(f"[START] {input_file}")
       try:
           completed = subprocess.run(
               command,
               stdout=subprocess.PIPE,
               stderr=subprocess.STDOUT,
               text=True,
               check=False,
               timeout=timeout_seconds,
           )
       except subprocess.TimeoutExpired:
           print(f"[TIMEOUT] {input_file} ({timeout_seconds} seconds)")
           return False
       except OSError as exc:
           print(f"[ERROR] Could not start IDA: {exc}")
           return False




       if completed.returncode == 0 and output_file.is_file():
           print(f"[OK]    {output_file}")
           return True




       print(f"[FAIL]  {input_file} (IDA exit code {completed.returncode})")
       if completed.stdout.strip():
           print(completed.stdout[-4000:])
       print(f"        Check log: {log_file}")
       return False








def main() -> int:
   parser = argparse.ArgumentParser(description=__doc__)
   parser.add_argument("--ida", required=True, type=Path,
                       help="Path to IDA Pro executable, e.g. /opt/idapro/idat64")
   parser.add_argument("--input", required=True, type=Path,
                       help="One executable or a folder containing executables")
   parser.add_argument("--output", required=True, type=Path,
                       help="Folder where .asm files will be stored")
   parser.add_argument("--recursive", action="store_true",
                       help="Search subfolders when --input is a directory")
   parser.add_argument("--timeout", type=int, default=600,
                       help="Maximum seconds per sample (default: 600)")
   parser.add_argument("--skip-existing", action="store_true",
                       help="Skip samples whose non-empty .asm file already exists")
   args = parser.parse_args()




   ida_path = args.ida.expanduser().resolve()
   if not ida_path.is_file() or not os.access(ida_path, os.X_OK):
       print(f"IDA executable is missing or not executable: {ida_path}",
             file=sys.stderr)
       return 2




   try:
       input_files = find_inputs(args.input.expanduser().resolve(), args.recursive)
   except FileNotFoundError as exc:
       print(str(exc), file=sys.stderr)
       return 2




   if not input_files:
       print("No Windows PE executable files were found.", file=sys.stderr)
       return 2




   if args.timeout <= 0:
       print("--timeout must be greater than zero.", file=sys.stderr)
       return 2




   output_dir = args.output.expanduser().resolve()
   output_dir.mkdir(parents=True, exist_ok=True)




   success_count = 0
   for input_file in input_files:
       if export_one(ida_path, input_file, output_dir,
                     args.timeout, args.skip_existing):
           success_count += 1




   failed_count = len(input_files) - success_count
   print(f"\nFinished: {success_count} succeeded, {failed_count} failed")
   return 0 if failed_count == 0 else 1








if __name__ == "__main__":
   raise SystemExit(main())
